version: '2'

services:
  zookeeper:
    container_name: zookeeper
    hostname: localhost
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka1:
    container_name: kafka1
    hostname: localhost
    image: bitnami/kafka:latest
    ports:
      - 9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka2:
    container_name: kafka2
    hostname: localhost
    image: bitnami/kafka:latest
    ports:
      - 9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka3:
    container_name: kafka3
    hostname: localhost
    image: bitnami/kafka:latest
    ports:
      - 9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
