apiVersion: v1
kind: Pod
metadata:
  name: posts-service
  labels:
    name: posts-service
spec:
  containers:
    - name: posts-service
      image: hisham13/posts-service:0.0.1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3331
