curl https://test.oppwa.com/v1/checkouts \
 -d "paymentType=DB" \
 -d "amount=92.00" \
 -d "currency=EUR" \
 -d "entityId=8a8294174d0595bb014d05d82e5b01d2" \
 -H "Authorization: Bearer OGE4Mjk0MTc0ZDA1OTViYjAxNGQwNWQ4MjllNzAxZDF8OVRuSlBjMm45aA=="