# Bitnami single kafka
version: "3"

services:
  zookeeper:
    container_name: zookeeper
    hostname: localhost
    image: bitnami/zookeeper:latest
    ports:
      - 4000:4000
    environment:
      - ZOO_PORT_NUMBER=4000
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    hostname: localhost
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:4000
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
