version: '3'

services:
  zookeeper:
    container_name: zookeeper
    hostname: localhost
    image: bitnami/zookeeper:latest
    ports:
     - 4000:4000
    environment:
     - ZOO_PORT_NUMBER=4000
     - ALLOW_ANONYMOUS_LOGIN=yes

  kafka1:
    container_name: kafka1
    hostname: localhost
    image: bitnami/kafka:latest
    ports:
      - 9091:9091
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9091
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:4000
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka2:
    container_name: kafka2
    hostname: localhost
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:4000
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka3:
    container_name: kafka3
    hostname: localhost
    image: bitnami/kafka:latest
    ports:
      - 9093:9093
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:4000
      - ALLOW_PLAINTEXT_LISTENER=yes
