version: "3"

services:
  prisma:
    image: prismagraphql/prisma:1.34
    container_name: graphql-prisma
    # restart: always
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            # MongoDB Connection
            connector: mongo
            uri: mongodb://admin:admin@host.docker.internal:27017
            database: graphql-prisma

# Post-grey SQL Connection
# connector: postgres
# host: host.docker.internal
# database: graphql-prisma
# schema: public
# user: postgres
# password: mysecretpassword
# ssl: false
# rawAccess: true
# port: '5432'
# migrations: true
