apiVersion: v1
kind: Service
metadata:
  name: events-bus-node-service
spec:
  type: NodePort
  selector:
    app: events-bus-service
  ports:
    - name: events-bus
      protocol: TCP
      port: 3335
      targetPort: 3335
