apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-bus-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-bus-service
  template:
    metadata:
      labels:
        app: events-bus-service
    spec:
      containers:
        - name: events-bus-service
          image: hisham13/events-bus-service

---
apiVersion: v1
kind: Service
metadata:
  name: events-bus-service-cluster-ip-srv
spec:
  selector:
    app: events-bus-service
  ports:
    - name: events-bus
      protocol: TCP
      port: 3335
      targetPort: 3335
