apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-service
  template:
    metadata:
      labels:
        app: posts-service
    spec:
      containers:
        - name: posts-service
          image: hisham13/posts-service
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service-cluster-ip-srv
spec:
  selector:
    app: posts-service
  ports:
    - name: posts
      protocol: TCP
      port: 3331
      targetPort: 3331
