apiVersion: v1
kind: Service
metadata:
  name: posts-node-service
spec:
  type: NodePort
  selector:
    app: posts-service
  ports:
    - name: posts
      protocol: TCP
      port: 3331
      targetPort: 3331
