version: "3"

services:
  shard2svr1:
    image: mongo
    container_name: shard2svr1
    command: mongod --shardsvr --replSet ${SHARD_2_RS_NAME} --dbpath /data/db --port 27017
    ports:
      - ${SHARD_2_CONTAINER_1_PORT}:27017
    volumes:
      - shard2svr1:/data/db

  shard2svr2:
    image: mongo
    container_name: shard2svr2
    command: mongod --shardsvr --replSet ${SHARD_2_RS_NAME} --dbpath /data/db --port 27017
    ports:
      - ${SHARD_2_CONTAINER_2_PORT}:27017
    volumes:
      - shard2svr2:/data/db

  shard2svr3:
    image: mongo
    container_name: shard2svr3
    command: mongod --shardsvr --replSet ${SHARD_2_RS_NAME} --dbpath /data/db --port 27017
    ports:
      - ${SHARD_2_CONTAINER_3_PORT}:27017
    volumes:
      - shard2svr3:/data/db

volumes:
  shard2svr1:
  shard2svr2:
  shard2svr3:
