version: "3"

services:
  shard3svr1:
    image: mongo
    container_name: shard3svr1
    command: mongod --shardsvr --replSet ${SHARD_3_RS_NAME} --dbpath /data/db --port 27017
    ports:
      - ${SHARD_3_CONTAINER_1_PORT}:27017
    volumes:
      - shard3svr1:/data/db

  shard3svr2:
    image: mongo
    container_name: shard3svr2
    command: mongod --shardsvr --replSet ${SHARD_3_RS_NAME} --dbpath /data/db --port 27017
    ports:
      - ${SHARD_3_CONTAINER_2_PORT}:27017
    volumes:
      - shard3svr2:/data/db

  shard3svr3:
    image: mongo
    container_name: shard3svr3
    command: mongod --shardsvr --replSet ${SHARD_3_RS_NAME} --dbpath /data/db --port 27017
    ports:
      - ${SHARD_3_CONTAINER_3_PORT}:27017
    volumes:
      - shard3svr3:/data/db

volumes:
  shard3svr1:
  shard3svr2:
  shard3svr3:
