/** Declaration file generated by dts-gen */

declare module 'paytabs_api' {
  export function createPayPage<T>(objData: T, callback: any): void;
  export function validateSecretKey<T>(objData: T, callback: any): void;
  export function verifyPayment<T>(objData: T, callback: any): void;
  //   const paytabs: any = {
  //     createPayPage,
  //     validateSecretKey,
  //     verifyPayment,
  //   };
  //   paytabs.createPayPage = createPayPage;
  //   paytabs.validateSecretKey = validateSecretKey;
  //   paytabs.verifyPayment = verifyPayment;
  //   export = paytabs;
}
